* **Configuration Options**

  Ever wondered what configuration options you have available to you in files
  such as ``app/config/config.yml``? In this section, all the available configuration
  is broken down by the key (e.g. ``framework``) that defines each possible
  section of your Symfony2 configuration.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* :doc:`Configuring the Kernel (e.g. AppKernel) </reference/configuration/kernel>`

* **Formuláře a validace**

  * :doc:`Přehled formulářových typů </reference/forms/types>`
  * :doc:`Přehled validačních pravidel </reference/constraints>`
  * :doc:`Seznam funkcí a proměnných dostupných v Twig šablonách </reference/forms/twig_reference>`

* :doc:`Přehled rozšíření pro Twig (formuláře, filtry, štítky, atd.)</reference/twig_reference>`

* **Ostatní**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/requirements`
