* **Zdrojový kód**

  * :doc:`Chyby </contributing/code/bugs>`
  * :doc:`Opravy </contributing/code/patches>`
  * :doc:`Zabezpečení </contributing/code/security>`
  * :doc:`Testy </contributing/code/tests>`
  * :doc:`Pravidla pro psaní kódu</contributing/code/standards>`
  * :doc:`Programátorské zásady</contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`
  * :doc:`Licence </contributing/code/license>`

* **Dokumentace**

  * :doc:`Přehled </contributing/documentation/overview>`
  * :doc:`Formátování </contributing/documentation/format>`
  * :doc:`Pravidla pro psaní dokumentace </contributing/documentation/standards>`
  * :doc:`Překlady </contributing/documentation/translations>`
  * :doc:`Licence </contributing/documentation/license>`

* **Komunita**

  * :doc:`Proces vývoje </contributing/community/releases>`
  * :doc:`IRC setkání </contributing/community/irc>`
  * :doc:`Další zdroje </contributing/community/other>`
